# Generated by Django 4.1.4 on 2022-12-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_post', models.URLField(default='', verbose_name='海报')),
                ('movie_introduce', models.TextField(verbose_name='内容简述')),
                ('movie_rate', models.PositiveSmallIntegerField(verbose_name='评分')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=32, verbose_name='名称')),
                ('movie_actor', models.CharField(max_length=32, verbose_name='演员')),
                ('movie_direct', models.CharField(max_length=32, verbose_name='导演')),
                ('movie_time', models.DateTimeField(auto_now_add=True, verbose_name='上映时间')),
                ('movie_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spider.moviedetail')),
            ],
        ),
    ]
