# Generated by Django 4.1.5 on 2023-01-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieDetail',
        ),
    ]
