# Generated by Django 4.1.4 on 2022-12-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='邮箱')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (2, '异常')], default=1, verbose_name='异常账号?')),
                ('avatar', models.URLField(blank=True, default='', null=True, verbose_name='头像地址')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['create_date'],
            },
        ),
    ]
