# Generated by Django 4.1.5 on 2023-05-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='status',
        ),
    ]
