# Generated by Django 4.1.5 on 2023-05-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPeriodicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('desc', models.TextField(default='', verbose_name='任务描述')),
            ],
            options={
                'verbose_name': '用户任务',
                'verbose_name_plural': '用户任务',
                'ordering': ['create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['create_time'], 'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['username', 'password'], name='name_pwd_idx'),
        ),
        migrations.AddField(
            model_name='userperiodictask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='userperiodictask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userinfo', verbose_name='用户与任务'),
        ),
    ]
