# Generated by Django 4.1.5 on 2023-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userperiodictask_alter_userinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userperiodictask',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
