# Generated by Django 4.1.5 on 2023-05-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userinfo_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperiodictask',
            name='desc',
        ),
    ]
